### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/putty-svn#1]
This Package will be removed in 7 days from KCP.

Reason: **Broken**

```
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://github.com/Gabrielgtx/putty-icons/releases/download/1.0/putty.png
```

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by Gabrielgtx** [comment]
thanks for the warning. I have updated the package :)
